// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"github.com/kenji-kk/mucom-go/internal/interface/handler"
	"github.com/kenji-kk/mucom-go/internal/repository"
	"github.com/kenji-kk/mucom-go/internal/usecase"
)

// Injectors from wire.go:

func InitializeRootHandlers() handler.RootHandlers {
	authRepository := repository.NewAuthRepository()
	authUsecase := usecase.NewAuthUsecase(authRepository)
	authHandler := handler.NewAuthHandler(authUsecase)
	rootHandlers := handler.NewRootHandlers(authHandler)
	return rootHandlers
}
