version: "3"

services:
  go:
    build: ./docker/go/
    ports:
      - 8080:8080
    container_name: go
    command: sh -c "go mod tidy && go install github.com/cosmtrek/air@latest && air -c .air.toml"
    depends_on:
      - postgres
    volumes:
      - ./:/app/api/
  
  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    restart: always
  
  pgAdmin4:
    image: dpage/pgadmin4
    volumes:
      - ./docker/postgres/pgadmin4_data:/var/lib/pgadmin
    ports:
      - "4040:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres

networks:
    default:
      name: app-network
