openapi: 3.0.0
info:
  version: 1.0.0
  title: Mucom
  license:
    name: keigo,haruki
servers:
  - url: http://petstore.swagger.io/
paths:
  /Reviews:
    get:
      summary: List all reviews
      operationId: listReview
      tags:
        - review
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 20)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of reviews
          headers:
            x-next: #なんの設定か不明
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reviews"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Review:
      required:
        - id
        - reviewDate
        - reviewTitle
        - reviewInfo
      properties:
        id:
          type: integer
          format: int64
          example: 1
        reviewDate:
          type: string
          format: date-time
          example: "2017-07-21T17:32:28Z"
        reviewTitle:
          type: string
          example: "ミセスの曲サイコー"
        reviewInfo:
          type: string
          example: "ミセスの曲は早いテンポの曲が多くてイケてる"
    Reviews:
      type: array
      items:
        $ref: "#/components/schemas/Review"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
