// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"github.com/kenji-kk/mucom-go/server/internal/interface/handler"
	"github.com/kenji-kk/mucom-go/server/internal/repository"
	"github.com/kenji-kk/mucom-go/server/internal/usecase"
)

// Injectors from wire.go:

func InitializeHandlers() handler.Handlers {
	authRepository := repository.NewAuthRepository()
	authUsecase := usecase.NewAuthUsecase(authRepository)
	authHandler := handler.NewAuthHandler(authUsecase)
	handlers := handler.NewHandlers(authHandler)
	return handlers
}
